NORMALIZATION PROBLEM

In [70]:
import numpy as np

In [71]:
X = np.random.random((5,5)) #create a randomized 5x5 array
Z = ((X - X.mean())/X.std()) #normalize each element in the array

In [72]:
np.save('X_normalized.npy',Z)

In [73]:
Y = np.load("X_normalized.npy")

In [74]:
print ("Normalized ndarray")
print (Y)

Normalized ndarray
[[ 1.41005335 -0.08897024 -1.0309969  -1.42224665  1.44873434]
 [-0.09958732 -0.39470142  0.34509894 -0.9679413  -1.45209808]
 [-1.05395303  1.18788133  1.1170923  -0.04466767 -1.35884713]
 [ 0.36052772  0.8827151   1.67637207  0.20964787  1.17364124]
 [-0.63003899 -0.96751295 -0.96921319  1.11992254 -0.45091194]]


DIVISIBLE BY 3 PROBLEM

In [75]:
i = 1
A = [] #list for squared numbers
B = [] #list for divisible numbers

for i in range (1,101): #loop to get the square from 1 to 100
    squared = i**2
    A.append(squared) #store squared numbers into the square list
    if i % 3 == 0: #condition to store a number into the divisible list
        B.append(squared)
        
sq = np.array(A) #store the square list into sq array
sq.resize(10,10) #resize the array into 10x10
div = np.array(B) #store the divisible list into div array
div.resize(3,11)

print("10x10 Squared Array")
print(sq)

10x10 Squared Array
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [76]:
np.save('div_by_3.npy',div)

In [77]:
C = np.load("div_by_3.npy")

In [78]:
print ("Divisible by 3")
print (C)

Divisible by 3
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
